### ISSUE TITLE
RoutingError after installation

### ISSUE THREAD

**Issue by dpalic** [taqueci/redmine_wysiwyg_editor#115]
After installation my wiki page stays emtpy and is unusable. How to fix this?

![image](https://user-images.githubusercontent.com/1399203/108310116-17f5c700-71b3-11eb-95e3-756d57bb197c.png)

environment:
ubuntu 18.04 with default redmine 3.4.4
cd /usr/share/redmine/plugins
git clone https://github.com/taqueci/redmine_wysiwyg_editor.git
chown -R www-data.www-data redmine_wysiwyg_editor

and getting this error in log

```
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_wysiwyg_editor/javascripts/tinymce/tinymce.min.js"):
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:38:in `call_app'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:22:in `call'
  /usr/lib/ruby/vendor_ruby/request_store/middleware.rb:9:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/request_id.rb:21:in `call'
  /usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:22:in `call'
  /usr/lib/ruby/vendor_ruby/rack/runtime.rb:18:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/static.rb:120:in `call'
  /usr/lib/ruby/vendor_ruby/rack/content_length.rb:15:in `call'
  /usr/lib/ruby/vendor_ruby/rack/sendfile.rb:113:in `call'
  /usr/lib/ruby/vendor_ruby/rails/engine.rb:518:in `call'
  /usr/lib/ruby/vendor_ruby/rails/application.rb:165:in `call'
  /usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `public_send'
  /usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

```

**Comment by taqueci** [comment]
Hi @dpalic 

Could you please tell me your environment and plugins?
(Administration » Information)

**Comment by dpalic** [comment]
sure

```
Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.9.7
  Mercurial                      4.5.3
  Git                            2.17.1
  Filesystem                     
Redmine plugins:
  computed_custom_field          1.0.6
```

**Comment by dpalic** [comment]
is there any update to this?
also can I somehow modify the code to test and report?
e.g. not clear there (in which file) the routes are defined, so I could try a local code modification)

**Comment by dpalic** [comment]
found my issue

https://github.com/taqueci/redmine_wysiwyg_editor/pull/117

**Comment by taqueci** [comment]
Merged.
Thank you!

**Comment by dpalic** [comment]
edited it once more
https://github.com/taqueci/redmine_wysiwyg_editor/pull/118
