### ISSUE TITLE
Can not install in redmine 5.0.4

### ISSUE THREAD

**Issue by howtoesc** [taqueci/redmine_wysiwyg_editor#166]
Remine env：[sameersbn/docker-redmine](https://github.com/sameersbn/docker-redmine) 5.0.4
Error installtion log：

```
redmine-redmine-1  | Installing gems required by plugins...
redmine-redmine-1  | You are replacing the current local value of without, which is currently "development:test"
redmine-redmine-1  | Migrating plugins. Please be patient, this could take a while...
redmine-redmine-1  | rake aborted!
redmine-redmine-1  | Redmine::PluginNotFound: Plugin not found. The directory for plugin redmine_wysiwyg_editor should be /home/redmine/redmine/plugins/redmine_wysiwyg_editor.
redmine-redmine-1  | /home/redmine/redmine/lib/redmine/plugin.rb:104:in `register'
redmine-redmine-1  | /home/redmine/redmine/plugins/redmine_wysiwyg_editor-master/init.rb:1:in `<top (required)>'
redmine-redmine-1  | /home/redmine/redmine/lib/redmine/plugin_loader.rb:31:in `load'
redmine-redmine-1  | /home/redmine/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
redmine-redmine-1  | /home/redmine/redmine/lib/redmine/plugin_loader.rb:108:in `each'
redmine-redmine-1  | /home/redmine/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
redmine-redmine-1  | /home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:367:in `require_environment!'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
redmine-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
redmine-redmine-1  | Tasks: TOP => redmine:plugins:migrate => environment
redmine-redmine-1  | (See full trace by running task with --trace)
redmine-redmine-1 exited with code 1

```

**Comment by taqueci** [comment]
Hi @howtoesc 

Please rename directory from `redmine_wysiwyg_editor-master` to `redmine_wysiwyg_editor`.

**Comment by howtoesc** [comment]
it's my fault
everything is fine now
Thank you so much
